[package]
name = "moonmoji"
version = "0.1.0"
authors = ["rickycodes <ricky.miller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timemoji = "0.1.0"
